### ISSUE TITLE
`docker-compose up -d` Results in container status exited

### ISSUE THREAD

**Issue by sbrendtro** [openach/docker-openach#2]
I followed the instructions and run this command `docker-compose up -d` but the container status is Exited. When I checked the docker logs, then I got below errors. 

```
AH00526: Syntax error on line 22 of /etc/apache2/sites-enabled/default-ssl.conf:
SSLCertificateFile: file '/etc/ssl/openach/openach.crt' does not exist or is empty
Action '-D FOREGROUND' failed.
The Apache error log may have more information.
```
Then I run the this command to check whether ssl certificate and key are there or not. 

`docker run -it --rm --name openACH openach/openach:latest bash`

I found that certificates are not empty. I don't understand why container not start and remains in exited status and also don't why apache can't read ssl certificates.

I am using unbuntu server. 

Please help me.

_Originally posted by @ramesh8830 in https://github.com/openach/docker-openach/issues/1#issuecomment-644808058_

**Comment by sbrendtro** [comment]
The following command runs the image as a container _without_ any volumes, so the contents of /etc/ssl/openach/ inside your container have the default files provided by the image, not your local /ssl/ folder.

```docker run -it --rm --name openACH openach/openach:latest bash```

The image's default files in the /etc/ssl/openach/ folder are:
```
     openach-self-signed.crt
     openach-self-signed.key
```

The Apache config for the site doesn't reference these files  It is looking for these instead:
```
                SSLCertificateFile      /etc/ssl/openach/openach.crt
                SSLCertificateKeyFile /etc/ssl/openach/openach.key
```

As to why the container isn't starting with `docker-compose up -d`, I would check your local `./ssl/openach` folder (found in the same folder as `docker-compose.yml`) to be sure it contains `openach.crt` and `openach.key`. By default these are symlinks to the .dist versions of the certificate/key files. If you created your own certificates, be sure to remove the symlinks and replace them with your own cert/key files, being careful to name them `openach.crt` and `openach.key`, respectively.

You can also just recreate relative symlinks for `openach.crt` and `openach.key` pointing to your cert/key files if you like, but the new cert/key files will need to be in the same folder. This is important because the `./ssl/` folder is mounted as a volume, and if your symlink points outside of that folder, it will not be referenced correctly when mounted by the container.

Let me know if that helps.

Steve

**Comment by ramesh8830** [comment]
do I need to make any changes insdie dockerfile for below lines? Those lines looks like copying the default self signed certificates.

```
RUN mkdir /etc/ssl/openach/
ADD ssl/openach/openach-self-signed.key.dist /etc/ssl/openach/openach-self-signed.key
ADD ssl/openach/openach-self-signed.crt.dist /etc/ssl/openach/openach-self-signed.crt
```

**Comment by sbrendtro** [comment]
While you could change those to copy to `openach.key` and `openach.crt`, as soon as you ran `docker-compose up -d`, the docker-compose.yml volume mapping would be mounted over the top of `/etc/ssl/openach/`, so you wouldn't see your image file changes.

When using docker-compose to manage your container, your suggested changes to the the Dockerfile are not necessary. Also, you do not need to use `docker run` - instead, you use the `docker exec` command to get into the container's command line:

```
    docker exec -it dockeropenach_web_1 /bin/bash
```

Again, this all assumes your local `./ssl/` folder looks like:
```
./ssl/openach/openach.crt    - Your certificate file (or relative symlink to it)
./ssl/openach/openach.key    - Your key file (or relative symlink to it)
```

**Comment by ramesh8830** [comment]
Thank you @sbrendtro . Creating symlink for my own ssl didn't work. created actual files with same name as openach.crt and openach.key did work for me. 

But pages are loading differently when https and http.

Below is the screenshot when I use http

![image](https://user-images.githubusercontent.com/56535842/84797527-8d533b80-b017-11ea-9197-5167444429e5.png)

Below is the screenshot when i use https

![image](https://user-images.githubusercontent.com/56535842/84797580-9cd28480-b017-11ea-9e32-387ffe86dca4.png)

thats how it works?

**Comment by sbrendtro** [comment]
Missing content over https is fixed in 1.9.1, just now updated the docker-openach repo to use that version. The following commands in your docker-compose cloned repo should fix it:
```
git pull origin master
docker-compose pull
docker-compose up -d
```

Also, note that the web interface is mainly for simplifying some admin tasks. API access and CLI are the primary ways one interacts with OpenACH.

**Comment by ramesh8830** [comment]
Thank you @sbrendtro . https is also working fine now.

**Comment by sbrendtro** [comment]
Good to hear.
