### ISSUE TITLE
Can't create Originator web UI

### ISSUE THREAD

**Issue by ramesh8830** [openach/docker-openach#3]
Hi

I can't able to create Originator from web ui. Getting below error while trying to create.

![image](https://user-images.githubusercontent.com/56535842/85640255-f0447280-b6a8-11ea-89aa-0e10b6f1f362.png)

Please help me

**Comment by sbrendtro** [comment]
Please note thatthe Web UI is being deprecated and doesn't always work as expected. We recommend sticking to the CLI. If you pull a copy of the latest docker-openach project (1.9.3), we included a new docker-compose friendly way of accessing the CLI.

```
   docker-compose run --rm cli
   docker-compose run --rm cli user create --user_login=johndoe --user_password=supersecret --user_email_address=johndoe@email.com --user_first_name=John --user_last_name=Doe
   docker-compose run --rm cli user setup --user_id=_user-id-from-previous-command_ --name="Test Originator" --identification=112358130 --routing_number=101000187 --account_number=1234567890
```
