### ISSUE TITLE
not able to create originator - Error: User Cannot be blank

### ISSUE THREAD

**Issue by rajeevvishva** [openach/docker-openach#4]
![image](https://user-images.githubusercontent.com/5356234/89769260-77935b80-db1a-11ea-8f48-125c4583d899.png)

**Comment by rajeevvishva** [comment]
also looking for sendbox details for testing... but still not found...

**Comment by ramesh8830** [comment]
./openach user setup --user_id=ced64f44-1959-443d-a38f-0178f650050d --name="Test Originator" --identification=112358130 --routing_number=101000187 --account_number=1234567890

Even command line didn't work for me to create originator using test and real values. Getting below error always.

Unable to find ODFI with routing number 101000187

**Comment by sbrendtro** [comment]
@rajeevvishva please note that the Web UI is being deprecated and doesn't always work as expected. We recommend sticking to the CLI. If you pull a copy of the latest docker-openach project (1.9.3), we included a new docker-compose friendly way of accessing the CLI.

```
   docker-compose run --rm cli
   docker-compose run --rm cli user create --user_login=johndoe --user_password=supersecret --user_email_address=johndoe@email.com --user_first_name=John --user_last_name=Doe
```
