### ISSUE TITLE
Can we use Openach as payment gateway?

### ISSUE THREAD

**Issue by ramesh8830** [openach/docker-openach#7]
Hi @sbrendtro 

Can we use openach as payment gateway in our application and collect payments using credit/debit cards in subscription kind of a system from users?

Please advise.

Thanks,
Ramesh

**Comment by sbrendtro** [comment]
Sorry... OpenACH focuses on ACH transactions (debit/credit via the FedACH system). As such, there is no mechanism in OpenACH to process credit/debit cards over Visa/Mastercard/AmEx networks.
